import type { Env } from './env';
import { validateTelegramSecret } from './env';
import { buildConfirmationPromptMessage, buildConfirmedMessage, buildEarlyWarningMessage, buildFinalizedReminderMessage, buildReminderMessage, buildWelcomeMessage } from './messages';
import { confirmSubscriber, findEnabledSubscribers, getSubscriber, markReminderSent, reminderWasSent, saveMessageId, upsertSubscriber } from './store';
import { initialReminderDate } from './time';
import { answerCallbackQuery, editTelegramMessage, sendTelegramMessage, setTelegramWebhook } from './telegram';
import { reminderStage } from './reminder';
type TelegramUpdate = { message?: { chat?: { id?: number }; text?: string }; callback_query?: { id: string; data?: string; message?: { chat?: { id?: number }; message_id?: number } } };
export async function runReminderCron(env: Env, now: Date): Promise<number> { const subscribers = await findEnabledSubscribers(env.DB); let sent = 0; for (const subscriber of subscribers) { const stage = reminderStage(now, new Date(subscriber.next_reminder_at)); if (!stage || await reminderWasSent(env.DB, subscriber.chat_id, subscriber.next_reminder_at, stage)) continue; try { const reminderAt = new Date(subscriber.next_reminder_at); const payload = stage === 'five_days' ? buildEarlyWarningMessage(reminderAt) : buildReminderMessage(reminderAt, stage); const messageId = await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, subscriber.chat_id, payload); await saveMessageId(env.DB, subscriber.chat_id, messageId, now); await markReminderSent(env.DB, subscriber.chat_id, subscriber.next_reminder_at, stage, now); sent += 1; } catch (error) { console.error('Reminder send failed', { chatId: subscriber.chat_id, error: String(error) }); } } return sent; }
export async function handleTelegramUpdate(update: TelegramUpdate, env: Env, now = new Date()): Promise<void> { const messageChatId = update.message?.chat?.id; const messageText = update.message?.text?.trim(); if (messageChatId && messageText === '/start') { const chatId = String(messageChatId); await upsertSubscriber(env.DB, chatId, now, initialReminderDate()); await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, buildWelcomeMessage()); return; } if (messageChatId && messageText === '/test') { const chatId = String(messageChatId); await upsertSubscriber(env.DB, chatId, now, initialReminderDate()); await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, buildReminderMessage(now)); return; } const callback = update.callback_query; const callbackChatId = callback?.message?.chat?.id; const callbackMessageId = callback?.message?.message_id; if (callback && callbackChatId !== undefined && callbackMessageId !== undefined && callback.data === 'confirm_keepalive' && await getSubscriber(env.DB, String(callbackChatId))) { await answerCallbackQuery(env.TELEGRAM_BOT_TOKEN, callback.id); await editTelegramMessage(env.TELEGRAM_BOT_TOKEN, String(callbackChatId), callbackMessageId, buildConfirmationPromptMessage()); return; } if (callback && callbackChatId !== undefined && callbackMessageId !== undefined && callback.data === 'confirm_keepalive_final' && await getSubscriber(env.DB, String(callbackChatId))) { const chatId = String(callbackChatId); const next = await confirmSubscriber(env.DB, chatId, now); await answerCallbackQuery(env.TELEGRAM_BOT_TOKEN, callback.id); await editTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, callbackMessageId, buildFinalizedReminderMessage(next)); await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, buildConfirmedMessage(next)); } }
export default { async fetch(request: Request, env: Env): Promise<Response> { const url = new URL(request.url); if (request.method === 'GET' && url.pathname === '/health') return new Response('ok'); if (request.method === 'GET' && url.pathname === '/setup') { await setTelegramWebhook(env.TELEGRAM_BOT_TOKEN, url.origin + '/telegram/webhook', env.WEBHOOK_SECRET); return new Response('Telegram webhook configured. You can now send /start to the bot.'); } if (request.method !== 'POST' || url.pathname !== '/telegram/webhook') return new Response('Not found', { status: 404 }); if (!validateTelegramSecret(request.headers.get('X-Telegram-Bot-Api-Secret-Token'), env.WEBHOOK_SECRET)) return new Response('Unauthorized', { status: 401 }); await handleTelegramUpdate(await request.json() as TelegramUpdate, env); return new Response('ok'); }, async scheduled(_controller: ScheduledController, env: Env): Promise<void> { await runReminderCron(env, new Date()); } };
