import type { Env } from './env';
import { validateTelegramSecret } from './env';
import { buildConfirmedMessage, buildReminderMessage, buildWelcomeMessage } from './messages';
import { confirmSubscriber, findDueSubscribers, getSubscriber, saveMessageId, upsertSubscriber } from './store';
import { initialReminderDate } from './time';
import { answerCallbackQuery, sendTelegramMessage } from './telegram';
type TelegramUpdate = { message?: { chat?: { id?: number }; text?: string }; callback_query?: { id: string; data?: string; message?: { chat?: { id?: number } } } };
export async function runReminderCron(env: Env, now: Date): Promise<number> { const due = await findDueSubscribers(env.DB, now); let sent = 0; for (const subscriber of due) { try { const messageId = await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, subscriber.chat_id, buildReminderMessage(new Date(subscriber.next_reminder_at))); await saveMessageId(env.DB, subscriber.chat_id, messageId, now); sent += 1; } catch (error) { console.error('Reminder send failed', { chatId: subscriber.chat_id, error: String(error) }); } } return sent; }
export async function handleTelegramUpdate(update: TelegramUpdate, env: Env, now = new Date()): Promise<void> { const messageChatId = update.message?.chat?.id; if (messageChatId && update.message?.text?.trim() === '/start') { const chatId = String(messageChatId); await upsertSubscriber(env.DB, chatId, now, initialReminderDate()); await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, buildWelcomeMessage()); return; } const callback = update.callback_query; const callbackChatId = callback?.message?.chat?.id; if (callback && callback.data === 'confirm_keepalive' && callbackChatId !== undefined) { const chatId = String(callbackChatId); if (await getSubscriber(env.DB, chatId)) { const next = await confirmSubscriber(env.DB, chatId, now); await answerCallbackQuery(env.TELEGRAM_BOT_TOKEN, callback.id); await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN, chatId, buildConfirmedMessage(next)); } } }
export default { async fetch(request: Request, env: Env): Promise<Response> { const url = new URL(request.url); if (request.method === 'GET' && url.pathname === '/health') return new Response('ok'); if (request.method !== 'POST' || url.pathname !== '/telegram/webhook') return new Response('Not found', { status: 404 }); if (!validateTelegramSecret(request.headers.get('X-Telegram-Bot-Api-Secret-Token'), env.WEBHOOK_SECRET)) return new Response('Unauthorized', { status: 401 }); await handleTelegramUpdate(await request.json() as TelegramUpdate, env); return new Response('ok'); }, async scheduled(_controller: ScheduledController, env: Env): Promise<void> { await runReminderCron(env, new Date()); } };
