import { addShanghaiCalendarDays, REMINDER_DAYS } from './time';
import type { ReminderStage } from './reminder';
export type Subscriber = { chat_id: string; next_reminder_at: string; last_confirmed_at: string; last_message_id: number | null; enabled: number };
export async function getSubscriber(db: D1Database, chatId: string): Promise<Subscriber | null> { return db.prepare('SELECT * FROM subscribers WHERE chat_id = ?1').bind(chatId).first<Subscriber>(); }
export async function upsertSubscriber(db: D1Database, chatId: string, now: Date, firstReminder: Date): Promise<boolean> { const existing = await getSubscriber(db, chatId); const nowIso = now.toISOString(); await db.prepare('INSERT INTO subscribers (chat_id, next_reminder_at, last_confirmed_at, last_message_id, enabled, created_at, updated_at) VALUES (?1, ?2, ?3, NULL, 1, ?3, ?3) ON CONFLICT(chat_id) DO UPDATE SET enabled = 1, updated_at = ?3').bind(chatId, firstReminder.toISOString(), nowIso).run(); return existing === null; }
export async function confirmSubscriber(db: D1Database, chatId: string, now: Date): Promise<Date> { const next = addShanghaiCalendarDays(now, REMINDER_DAYS); await db.prepare('UPDATE subscribers SET last_confirmed_at = ?2, next_reminder_at = ?3, updated_at = ?2 WHERE chat_id = ?1 AND enabled = 1').bind(chatId, now.toISOString(), next.toISOString()).run(); return next; }
export async function findDueSubscribers(db: D1Database, now: Date): Promise<Subscriber[]> { const result = await db.prepare('SELECT * FROM subscribers WHERE enabled = 1 AND next_reminder_at <= ?1 ORDER BY next_reminder_at ASC').bind(now.toISOString()).all<Subscriber>(); return result.results; }
export async function findEnabledSubscribers(db: D1Database): Promise<Subscriber[]> { const result = await db.prepare('SELECT * FROM subscribers WHERE enabled = 1 ORDER BY next_reminder_at ASC').all<Subscriber>(); return result.results; }
export async function reminderWasSent(db: D1Database, chatId: string, nextReminderAt: string, stage: ReminderStage): Promise<boolean> { return Boolean(await db.prepare('SELECT 1 FROM reminder_notifications WHERE chat_id = ?1 AND next_reminder_at = ?2 AND stage = ?3').bind(chatId, nextReminderAt, stage).first()); }
export async function markReminderSent(db: D1Database, chatId: string, nextReminderAt: string, stage: ReminderStage, now: Date): Promise<void> { await db.prepare('INSERT OR IGNORE INTO reminder_notifications (chat_id, next_reminder_at, stage, sent_at) VALUES (?1, ?2, ?3, ?4)').bind(chatId, nextReminderAt, stage, now.toISOString()).run(); }
export async function saveMessageId(db: D1Database, chatId: string, messageId: number, now: Date): Promise<void> { await db.prepare('UPDATE subscribers SET last_message_id = ?2, updated_at = ?3 WHERE chat_id = ?1').bind(chatId, messageId, now.toISOString()).run(); }
